# Autogenerated file
def render(module2_value):
    yield """<html><head><meta charset=UTF-8 /><meta name=viewport content=\"width=device-width, initial-scale=1\" /><title>k.sys UIserver</title><link rel=icon type=image/x-icon href=/static/img/favi.png><link rel=stylesheet href=static/css/entireframework.min.css /><link rel=stylesheet href=static/css/switchboard.css /><script src=\"static/js/switchboard.js\"></script></head><body><button class=\"btn-close btn btn-sm\">×</button><div class=card><div class=container><div class=hero><div class=toggle-div><p class=label>Switch 2</p><input type=checkbox id=2 onclick=toggleButtonSwitch2() """
    if module2_value==1:
        yield """ checked """
    yield """ /> <label for=2>Toggle</label></div></div></div></div></body></html>"""
