# Autogenerated file
def render(*a, **d):
    yield """<html lang=en><head><meta charset=UTF-8><meta name=viewport content=\"width=device-width, initial-scale=1.0\"><link rel=icon type=image/x-icon href=/static/img/favi.png><title>Submit Variables</title><style>body"""
    yield """{font-family:Arial,sans-serif;background:#f0f0f0;color:#333;margin:0;padding:0;display:flex;justify-content:center;align-items:center;height:100vh;}.container"""
    yield """{background:#fff;padding:20px;border-radius:8px;box-shadow:0 0 10px rgba(0,0,0,0.1);width:100%;max-width:600px;}h1"""
    yield """{text-align:center;margin-bottom:20px;}.form-group"""
    yield """{margin-bottom:15px;}label"""
    yield """{display:block;margin-bottom:5px;font-weight:bold;}input[type=\"number\"]"""
    yield """{width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;box-sizing:border-box;}button"""
    yield """{display:block;width:100%;padding:10px;background-color:#007bff;color:#fff;border:none;border-radius:4px;font-size:16px;cursor:pointer;margin-top:10px;}button:hover"""
    yield """{background-color:#0056b3;}.response"""
    yield """{text-align:center;margin-top:20px;}</style></head><body><nav class=nav tabindex=-1 onclick=this.focus()><div class=container><img href=/ src=/static/img/home.png style=\"width:30px; height:30px;\" alt=\"\" class=icon></div></nav><div class=container><h1>Submit Variables</h1><form id=form1><div class=form-group><label for=variable1>Variable 1:</label> <input type=number id=variable1 name=variable1 required></div><button type=submit>Submit Variable 1</button></form><form id=form2><div class=form-group><label for=variable2>Variable 2:</label> <input type=number id=variable2 name=variable2 required></div><button type=submit>Submit Variable 2</button></form><form id=form3><div class=form-group><label for=variable3>Variable 3:</label> <input type=number id=variable3 name=variable3 required></div><button type=submit>Submit Variable 3</button></form><div class=response id=response></div></div><script>
        document.addEventListener('DOMContentLoaded', function() """
    yield """{
            const forms = ['form1', 'form2', 'form3'];
            forms.forEach(formId => """
    yield """{
                const form = document.getElementById(formId);
                form.addEventListener('submit', function(event) """
    yield """{
                    event.preventDefault();
                    const formData = new FormData(form);
                    const data = """
    yield """{};
                    formData.forEach((value, key) => data[key] = parseInt(value, 10));
                    fetch('/submit', """
    yield """{
                        method: 'POST',
                        headers: """
    yield """{
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify(data)
                    })
                    .then(response => response.text())
                    .then(text => """
    yield """{
                        document.getElementById('response').innerText = text;
                        form.reset();
                    })
                    .catch(error => """
    yield """{
                        document.getElementById('response').innerText = 'Error: ' + error;
                    });
                });
            });
        });
    </script></body></html>"""
